# Roteiro da apostila: textos baseados na narração de cada videoaula; prints e destaques em % do quadro do vídeo.
def H(x, y, w, h, rotulo=''):
    return {'x': x, 'y': y, 'w': w, 'h': h, 'rotulo': rotulo}

AREA = {'id': 'estoque', 'nome': 'Operações de Estoque'}

BTA_MENU = [24, 17, 53, 60]      # janela "Controle Remanejo Loja" na área de trabalho
BTA_JANELA = [5.5, 4, 91, 86]   # janelas do BTA não maximizadas
TELA_CHEIA = [0, 0, 100, 96.5]   # sem a barra de tarefas
TOPO = [0, 0, 100, 64]           # telas maximizadas: só a parte com conteúdo
SETA = [4, 0, 92, 96.5]          # SETA (retaguarda), sem os ícones laterais

MODULOS = [
# ---------------------------------------------------------------- 1. RECEBIMENTO
{
 'id': 'recebimento', 'ordem': 1, 'nome': 'Recebimento de Mercadoria', 'duracao': '11:19', 'accent': '#2dd4bf',
 'objetivo': 'Dar entrada, no **BTA**, nos volumes que chegam do CD ou de um remanejo, conferindo **par a par** o que veio dentro de cada caixa antes de receber. Assim o estoque da loja fica igual ao físico e toda falta, sobra ou produto trocado é registrado na hora.',
 'quando': ['Sempre que o caminhão entregar volumes na loja (reposição do CD ou remanejo de outra loja).',
            'O procedimento é o mesmo para CD e remanejo; muda apenas o conteúdo das caixas.'],
 'antes': ['Tenha em mãos o **papel da Expedição** entregue com a mercadoria.',
           'Separe todas as caixas (volumes) e o leitor de código de barras. **Não é permitido digitar** códigos: tudo é bipado.'],
 'passos': [
  {'t': 13, 'titulo': 'Abra o BTA e entre em Expedição → Receber',
   'texto': ['No **Controle Remanejo Loja**, clique na aba **Expedição** e depois no botão **Receber**.'],
   'prints': [{'t': 20, 'crop': BTA_MENU, 'hl': [H(38.5, 24, 5.5, 4, '1'), H(26.5, 34, 46.5, 4.6, '2 · Receber')]}]},
  {'t': 34, 'titulo': 'Localize a expedição no papel',
   'texto': ['O papel da Expedição traz o **número da expedição**, a lista de volumes, o **total de volumes** e o **total de itens**. É o **código de barras** dele que você vai bipar.'],
   'prints': [{'t': 37, 'crop': [23, 4, 54, 88], 'hl': [H(40, 6, 18.5, 5, 'Nº da expedição'), H(61, 15.5, 13.5, 8, 'bipe este código'), H(23.5, 55.5, 17, 7, 'totais')]}]},
  {'t': 43, 'titulo': 'Bipe a expedição',
   'texto': ['Na tela **Receber Expedição**, bipe o código do papel. Aparecem os volumes da expedição em **vermelho**: vermelho = volume ainda não conferido.',
             'Uma expedição do CD normalmente tem vários volumes, um ao lado do outro.'],
   'prints': [{'t': 86, 'crop': BTA_JANELA, 'hl': [H(24, 16.3, 12.8, 3.4, 'expedição bipada'), H(24.6, 22.4, 14.8, 26.2, 'volume pendente')]}]},
  {'t': 101, 'titulo': 'Encontre a etiqueta de cada caixa',
   'texto': ['Cada caixa tem uma etiqueta de volume (azul ou amarela). O **número do volume** aparece embaixo do código de barras e também no quadrado vermelho do sistema.',
             'Separe as caixas e **bipe uma a uma** para fazer o recebimento.'],
   'prints': [{'t': 107, 'crop': [34, 2, 32, 88], 'hl': [H(43, 46, 18, 11.5, 'código do volume')]}]},
  {'t': 131, 'titulo': 'Bipe o volume e confira os produtos da caixa',
   'texto': ['Ao bipar a etiqueta da caixa abre a lista do que **deveria** estar dentro dela. Confira as colunas:',
             '**Qtde** = o que tem que ter na caixa · **Qtde Lida** = o que você bipou · **Diferença** = controle (tem que zerar).',
             'Bipe **todos os pares** que estão na caixa no campo **Código de Barras**.'],
   'prints': [{'t': 141, 'crop': TOPO, 'hl': [H(20.3, 7, 14.7, 5.5, 'bipe cada par'), H(71.5, 12, 17, 25, 'Qtde · Lida · Diferença')]}]},
  {'t': 166, 'titulo': 'Tudo batendo: aparece o ✔',
   'texto': ['Quando a quantidade lida bate com a esperada, a diferença de todos os tamanhos fica **0** e o sistema mostra o sinal de **OK**. Nesse caso é só usar **Receber Total**.'],
   'prints': [{'t': 176, 'crop': TELA_CHEIA, 'hl': [H(83, 12, 5.5, 25, 'diferença 0'), H(2, 68, 11, 14, 'OK'), H(0.3, 11.2, 11, 4.2, 'Receber Total')]}]},
  {'t': 191, 'titulo': 'Bipou errado? Use F7 para Retirar',
   'texto': ['A tecla **F7** alterna o botão entre **Adicionar** e **Retirar**. Em **Retirar**, bipe o par que foi lido a mais para tirá-lo da contagem; aperte **F7** de novo para voltar a **Adicionar**.',
             'Por isso é importante **conferir antes de receber**: se você bipar errado e não corrigir, a divergência não vai ser identificada.'],
   'prints': [{'t': 195, 'crop': TOPO, 'hl': [H(34.5, 6.8, 6.5, 3.8, 'Retirar (F7)')]}]},
  {'t': 255, 'titulo': 'Divergência de verdade: informe o Motivo',
   'texto': ['Se depois de conferir a caixa a diferença continuar, escolha o **Motivo** na linha do produto:',
             'Diferença **-1** (veio a menos) = **Falta de item** · Diferença **+1** (veio a mais) = **Sobra de item**. A lista também tem grade diferente, cor diferente, pé trocado, produto com defeito, sujo, manchado etc.'],
   'prints': [{'t': 274, 'crop': TOPO, 'hl': [H(83, 25.2, 5, 5.8, 'diferença'), H(88.2, 26.3, 9.2, 30, 'Motivo')]}]},
  {'t': 303, 'titulo': 'Produto que não é da caixa (intruso)',
   'texto': ['Se você bipar um par que não pertence ao volume aparece: **"Produto não deveria estar no volume, verifique!"**. Clique em **OK** antes de bipar qualquer outra coisa. Se bipar outro produto com a mensagem aberta, a tela fecha e aquele par **não é computado**.',
             'O intruso entra em **vermelho** no fim da lista, como sobra. Conte de novo e avise o **gestor** e a **Auditoria/Controladoria** para verificarem por que o produto chegou a mais (ou a menos).'],
   'prints': [{'t': 313, 'crop': TOPO, 'hl': [H(38.2, 41, 24.8, 20, 'clique em OK')]},
              {'t': 352, 'crop': TOPO, 'hl': [H(12, 36.3, 84.5, 3.6, 'intruso = sobra')]}]},
  {'t': 419, 'titulo': 'Motivo sem divergência não ajusta nada',
   'texto': ['Se o par veio **trocado, sujo ou com defeito** e mesmo assim você **bipou**, o sistema entende que está tudo OK, **mesmo que você escolha um motivo**. Primeiro gere a divergência (retire o par com F7, deixando a linha em vermelho) e só então informe o motivo.',
             'Ordem certa: **bipa o volume → confere os pés → dá baixa**. Nunca receba a nota para conferir depois.'],
   'dica': 'Motivo só vale para linha com diferença. Linha sem diferença = sem divergência.'},
  {'t': 536, 'titulo': 'Receber Parcial (quando há divergência)',
   'texto': ['Com falta, sobra ou intruso informados, clique em **Receber Parcial**. O sistema pede confirmação: **"Para prosseguir com o recebimento parcial, selecione o motivo da divergência para cada item"**. Responda **Sim**.'],
   'prints': [{'t': 541, 'crop': TOPO, 'hl': [H(0.3, 16.2, 11, 4.2, 'Receber Parcial'), H(36.2, 40.8, 28.6, 20.6, 'Sim')]}]},
  {'t': 559, 'titulo': 'Imprimir as etiquetas OLA',
   'texto': ['Em seguida ele pergunta se deseja **imprimir as etiquetas OLA** (os códigos dos produtos). **Na loja, responda Sim**: as etiquetas saem na impressora de etiquetas (Argox/Elgin) para selar os produtos que chegaram.',
             'No **remanejo** não é preciso tirar etiqueta, porque o produto já vem etiquetado da outra loja.'],
   'prints': [{'t': 559, 'crop': TOPO, 'hl': [H(35.5, 41, 30, 20, 'loja: Sim')]}]},
  {'t': 578, 'titulo': 'Volume amarelo = recebido com divergência',
   'texto': ['O volume fica **amarelo** quando foi recebido parcialmente. Se você perceber que a divergência foi um erro de leitura, bipe o volume de novo, ajuste com F7 (retirar/adicionar) até a diferença zerar e use **Receber Total**.'],
   'prints': [{'t': 577, 'crop': BTA_JANELA, 'hl': [H(24.6, 22.4, 14.8, 26.2, 'com divergência')]}]},
  {'t': 668, 'titulo': 'Volume verde e Finalizar',
   'texto': ['Com todos os volumes **verdes** (ou amarelos já tratados), clique em **Finalizar**. A nota é fechada e a mercadoria entra no estoque da loja.'],
   'prints': [{'t': 669, 'crop': BTA_JANELA, 'hl': [H(24.6, 22.6, 14.6, 26, 'recebido'), H(12.3, 18, 11, 3.8, 'Finalizar')]}]},
 ],
 'atencao': ['**Nunca digite** o código: o sistema só aceita leitura pelo leitor ("Não é permitido digitar, bipe o produto usando o leitor de código de barras!").',
             'Confira os pares **antes** de receber. Receber e conferir depois é procedimento errado e esconde divergência.',
             'Motivo sem diferença (linha bipada) **não ajusta nada** no sistema.',
             'Falta, sobra ou produto intruso deve ser comunicado ao **gestor** e à **Auditoria/Controladoria**.',
             'Mensagem de erro aberta: clique em **OK** antes de bipar o próximo par.'],
 'checklist': ['Papel da Expedição em mãos e caixas separadas',
               'Expedição bipada em Expedição → Receber',
               'Cada volume bipado e todos os pares conferidos',
               'Diferença zerada ou motivo informado (falta / sobra / intruso)',
               'Receber Total ou Receber Parcial',
               'Etiquetas OLA impressas (mercadoria do CD)',
               'Todos os volumes verdes/amarelos e Finalizar',
               'Divergências comunicadas ao gestor e à Auditoria'],
},
# ---------------------------------------------------------------- 2. NOTAS FISCAIS
{
 'id': 'notas-fiscais', 'ordem': 2, 'nome': 'Notas Fiscais', 'duracao': '11:39', 'accent': '#38bdf8',
 'objetivo': 'Gerar e imprimir, no **SETA (Retaguarda)**, a nota fiscal da transferência que você montou (remanejo, defeito ou devolução), com a **transportadora RL** e a **quantidade de volumes** corretas. Também mostra como **reimprimir** uma nota que não saiu.',
 'quando': ['Depois de fechar os volumes, imprimir os rótulos e fazer o **checkout da expedição**.',
            'Vale para toda nota enviada: remanejo, defeito, devolução ao CD ou devolução para outra loja.'],
 'antes': ['Tenha em mãos o **papel da Expedição** (número da expedição, quantidade de volumes e de itens).'],
 'passos': [
  {'t': 51, 'titulo': 'Abra o SETA e entre na Retaguarda',
   'texto': ['Entre no **SETA** com o usuário da sua loja e clique em **5 : Retaguarda**.'],
   'prints': [{'t': 57, 'crop': [18, 30, 64, 60], 'hl': [H(61.3, 57, 8.8, 17.5, 'Retaguarda')]}]},
  {'t': 12, 'titulo': 'Confira o papel da Expedição',
   'texto': ['O número da expedição desse papel é o que vai aparecer na transferência. A quantidade de volumes dele é a que vai na nota.'],
   'prints': [{'t': 35, 'crop': [23, 4, 54, 88], 'hl': [H(40, 6, 18.5, 5, 'Nº da expedição'), H(23.5, 55.5, 17, 7, 'volumes / itens')]}]},
  {'t': 76, 'titulo': 'Clique em TR e depois em Pesquisar',
   'texto': ['Na barra lateral, clique no ícone **TR** (Transferências de produtos entre filiais). Na tela que abre, clique em **5 - Pesquisar**.'],
   'prints': [{'t': 87, 'crop': SETA, 'hl': [H(0.8, 40.5, 3, 6, 'TR'), H(11.8, 27, 11.5, 3.3, 'Pesquisar')]}]},
  {'t': 97, 'titulo': 'Filtre: Transf. Enviadas + Pendentes',
   'texto': ['Em **Localizar transferência**, deixe marcado **Transf. Enviadas** e status **Pendentes** (já vêm assim) e clique em **Filtrar**.',
             'Recebidas/Canceladas servem só para consultar o que aconteceu com uma nota antiga.'],
   'prints': [{'t': 94, 'crop': SETA, 'hl': [H(26.4, 34.5, 9.5, 11, 'Enviadas + Pendentes'), H(26.4, 21.4, 6, 3.5, 'Filtrar')]}]},
  {'t': 131, 'titulo': 'Abra a transferência com a nota em branco',
   'texto': ['Toda transferência nova aparece com a coluna **Nota Fiscal em branco**: é essa que você vai gerar. Dê **dois cliques** nela.'],
   'prints': [{'t': 143, 'crop': SETA, 'hl': [H(37.5, 24.6, 34, 3, 'nota em branco')]}]},
  {'t': 176, 'titulo': 'Confira a expedição e clique em Enviar',
   'texto': ['Aparecem os produtos da transferência. Em **Observações** confira se o **número da expedição** é o mesmo do papel. Origem e destino já vêm preenchidos: **não mexa**.',
             'Bateu? Clique em **Enviar** e informe seu **usuário e senha**.'],
   'prints': [{'t': 182, 'crop': SETA, 'hl': [H(24.5, 85.5, 15, 4, 'nº da expedição'), H(76.5, 15.2, 9, 3.6, 'Enviar')]},
              {'t': 231, 'crop': SETA, 'hl': [H(31.6, 36.5, 36.8, 25, 'usuário e senha')]}]},
  {'t': 261, 'titulo': 'NÃO emita ainda: primeiro F7 - Transportador',
   'texto': ['Na tela **Impressão de Notas Fiscais**, **não clique em Emitir primeiro**. Clique antes em **F7 - Transportador**.',
             'Na janela **Transportador/Volumes** preencha a **Transportadora**, a **Quantidade** de volumes (fez 6 volumes = 6; um volume só = 1) e a **Espécie: VOLUME**.'],
   'prints': [{'t': 294, 'crop': SETA, 'hl': [H(12.5, 14, 9, 3.2, 'F7 - Transportador'), H(44.5, 34.3, 20, 3.4, 'Transportadora'), H(44.5, 50.5, 10, 7.5, 'Qtde + Espécie')]}]},
  {'t': 305, 'titulo': 'Transportadora: digite RL e dê Enter',
   'texto': ['Na lupa da transportadora abre o cadastro com várias empresas. Digite **RL** no campo de busca e dê **Enter**: aparece só a transportadora correta. Selecione, dê **Enter** e **OK**.',
             '**Sempre RL**, em qualquer nota: remanejo, defeito, devolução para loja ou para o CD.'],
   'prints': [{'t': 357, 'crop': SETA, 'hl': [H(31.5, 72.2, 24.5, 3.4, 'digite RL + Enter')]}]},
  {'t': 395, 'titulo': 'Agora sim: F8 - Emitir',
   'texto': ['Com transportadora e volumes preenchidos, clique em **F8 - Emitir**. Se perguntar que o campo de informações complementares está vazio, responda **Sim**.'],
   'prints': [{'t': 401, 'crop': SETA, 'hl': [H(12.5, 11.3, 9, 3.2, 'F8 - Emitir'), H(35.3, 41, 29.8, 19.5, 'Sim')]}]},
  {'t': 413, 'titulo': 'Anote o número e imprima',
   'texto': ['A nota é transmitida e abre o **Log Documentos Eletrônicos** com o **número da nota fiscal**. Clique em **Imprimir**, escolha a impressora da loja e imprima.'],
   'prints': [{'t': 418, 'crop': SETA, 'hl': [H(34.5, 31.5, 21, 3.5, 'nº da nota'), H(24.3, 32.8, 8.8, 3, 'Imprimir')]}]},
  {'t': 441, 'titulo': 'Reimprimir: Fiscal → Consulta Nota Fiscal Eletrônica',
   'texto': ['A nota não saiu na impressora e a tela foi fechada? No SETA, abra o menu **Fiscal → Consulta Nota Fiscal Eletrônica**.'],
   'prints': [{'t': 474, 'crop': SETA, 'hl': [H(22, 3, 3.2, 3, 'Fiscal'), H(22.5, 10.6, 17, 2.9, 'Consulta NF-e')]}]},
  {'t': 484, 'titulo': 'Ajuste o status e depois a data',
   'texto': ['Mude o **Status** (a nota já foi enviada; na dúvida use **Todos**). **Só depois** ajuste a **Data Inicial/Final**: toda vez que muda o status, a data volta para 2024. Se tiver o número da nota ou a TRF, pode filtrar por ele.',
             'Clique em **F8 - Filtrar**.'],
   'prints': [{'t': 482, 'crop': SETA, 'hl': [H(49, 44, 15, 3.2, 'Status (1º)'), H(49, 49.3, 8, 5.6, 'Datas (2º)'), H(31, 32.3, 6, 3, 'Filtrar')]}]},
  {'t': 591, 'titulo': 'Localize a nota pela hora e abra',
   'texto': ['Aparecem as notas do período. Se fez mais de uma no dia, identifique pela **hora** e pela quantidade. Selecione e clique em **Abrir NFE**.'],
   'prints': [{'t': 591, 'crop': SETA, 'hl': [H(25, 12.4, 61, 6.4, 'notas do dia'), H(13.5, 12.6, 6, 3, 'Abrir NFE')]}]},
  {'t': 621, 'titulo': 'Confira a transportadora e emita de novo',
   'texto': ['A nota abre na mesma tela. Se a transportadora estiver errada, corrija para **RL** em F7. Clique em **F8 - Emitir** e imprima.',
             '**Não feche a tela** até conferir que a nota saiu na impressora. Se fechar, terá que fazer a consulta de novo.'],
   'prints': [{'t': 632, 'crop': SETA, 'hl': [H(44.8, 34.3, 19, 3.4, 'tem que ser RL')]}]},
 ],
 'atencao': ['Transportadora é **sempre RL**. Nunca emita sem preencher o F7 - Transportador.',
             'A **quantidade de volumes** da nota tem que ser igual à do papel da Expedição.',
             'Confira o **número da expedição** nas Observações antes de clicar em Enviar.',
             'Na consulta de NF-e, mude o **status primeiro** e a **data depois** (a data volta para 2024).',
             'Só feche a tela de impressão depois de ver a nota impressa.'],
 'checklist': ['Papel da Expedição em mãos',
               'SETA → Retaguarda → TR → Pesquisar (Enviadas + Pendentes)',
               'Transferência com nota em branco aberta (2 cliques)',
               'Nº da expedição conferido e Enviar com usuário/senha',
               'F7 - Transportador: RL, quantidade de volumes e espécie VOLUME',
               'F8 - Emitir e nota impressa',
               'Número da NF anotado na placa do volume'],
},
# ---------------------------------------------------------------- 3. EMITIR ETIQUETAS
{
 'id': 'fazer-etiquetas', 'ordem': 3, 'nome': 'Emitir Etiquetas', 'duracao': '06:09', 'accent': '#fb923c',
 'objetivo': 'Gerar e imprimir, no **SETA**, as etiquetas de código de barras dos produtos (etiquetas avulsas) na impressora de etiquetas da loja, escolhendo o tipo e o modelo corretos.',
 'quando': ['Produto sem etiqueta, etiqueta rasurada, ilegível ou com código errado.',
            'Reposição de etiquetas de produtos da loja (por tamanho ou para toda a grade).'],
 'antes': ['Tenha o **código do produto** (ou use a lupa para pesquisar por marca/descrição).',
           'Confira se a impressora de etiquetas está ligada e com etiquetas.'],
 'passos': [
  {'t': 16, 'titulo': 'Estoque → Gerar Etiquetas de Produtos',
   'texto': ['No SETA (Retaguarda), abra o menu **Estoque** e clique em **Gerar Etiquetas de Produtos**.'],
   'prints': [{'t': 16, 'crop': SETA, 'hl': [H(13.3, 3.1, 3.7, 2.8, 'Estoque'), H(13.3, 45, 24, 3, 'Gerar Etiquetas de Produtos')]}]},
  {'t': 22, 'titulo': 'Escolha a aba Etiquetas Avulsas',
   'texto': ['A tela abre em **Etiquetas das Compras** (usada com o código da compra). Para etiquetar produtos da loja, clique em **Etiquetas Avulsas**.'],
   'prints': [{'t': 22, 'crop': SETA, 'hl': [H(55.5, 32, 17, 3.4, 'Etiquetas Avulsas')]}]},
  {'t': 60, 'titulo': 'Informe o produto e a quantidade',
   'texto': ['Em **Código do Produto**, digite o código com o tamanho (ex.: 007421-39) ou use a **lupa** para pesquisar. Confira a descrição, a cor e a referência que aparecem.',
             'Informe o **Nº de Etiquetas**. Para gerar etiquetas de **todos os tamanhos** conforme o estoque, marque **"Gerar etiquetas para todas as grades do produto"**.',
             'Clique em **Imprimir** para mandar o produto para a lista de impressão.'],
   'prints': [{'t': 64, 'crop': SETA, 'hl': [H(48.3, 40.5, 8.5, 3.2, 'código'), H(48.3, 58.6, 7, 3.2, 'nº etiquetas'), H(48, 63.2, 18.5, 4.8, 'todas as grades'), H(27.8, 33.8, 5.8, 3.2, 'Imprimir')]}]},
  {'t': 245, 'titulo': 'Não sabe o código? Pesquise pela lupa',
   'texto': ['A lupa abre a **Pesquisa de produtos**. Filtre pela **Marca** (ou descrição, referência) e clique em **F8 - Filtrar**. À direita aparecem os **tamanhos e quantidades** em estoque do produto selecionado.'],
   'prints': [{'t': 263, 'crop': SETA, 'hl': [H(13.5, 50.8, 11.5, 3.2, 'Marca'), H(13.5, 9.7, 6.5, 3, 'F8 - Filtrar'), H(74.5, 10.8, 11, 20, 'tamanhos')]}]},
  {'t': 108, 'titulo': 'Confira a lista e as opções de impressão',
   'texto': ['Na **Impressão de Etiquetas de Produtos** confira os produtos, tamanhos e quantidades. Selecione a **impressora** da loja, o tipo **Etiqueta Adesiva** e o modelo (**A - Uma com Preço**, B - Uma sem Preço etc.).',
             'Clique em **Imprimir**.'],
   'prints': [{'t': 108, 'crop': SETA, 'hl': [H(29, 21.8, 51, 16.2, 'produtos'), H(17.4, 39.3, 9.5, 3.4, 'impressora'), H(17.4, 51.8, 9.5, 6.8, 'tipo'), H(17.4, 61.8, 10.5, 13, 'modelo'), H(17.4, 21, 6, 3.2, 'Imprimir')]}]},
  {'t': 168, 'titulo': 'Selecione o modelo da etiqueta e dê OK',
   'texto': ['Em **Modelo da Etiqueta**, escolha o modelo da impressora da loja e clique em **Ok**.'],
   'prints': [{'t': 170, 'crop': SETA, 'hl': [H(42.8, 50.2, 22.3, 3.3, 'modelo'), H(32.4, 46.4, 8.2, 3.3, 'Ok')]}]},
  {'t': 184, 'titulo': 'Confira as etiquetas impressas',
   'texto': ['Cada etiqueta sai com **código de barras, descrição, marca, cor e tamanho**. Confira se o tamanho da etiqueta é o mesmo do par antes de colar.'],
   'prints': [{'t': 196, 'crop': [32, 4, 36, 86], 'hl': []}]},
  {'t': 223, 'titulo': 'Limpe o arquivo de etiquetas',
   'texto': ['Depois de imprimir, o sistema pergunta **"Deseja limpar o arquivo de etiquetas?"**. Responda **Sim** para a próxima impressão não repetir as etiquetas antigas.'],
   'prints': [{'t': 223, 'crop': SETA, 'hl': [H(39.5, 41, 21.2, 19.6, 'Sim')]}]},
 ],
 'atencao': ['Confira **código, cor e tamanho** antes de imprimir: etiqueta errada gera divergência no caixa e no estoque.',
             'Use **Etiquetas Avulsas** para produtos da loja; **Etiquetas das Compras** é pelo código da compra.',
             'Etiqueta rasurada ou falhada deve ser **reimpressa**, nunca aproveitada.',
             'Sempre **limpe o arquivo de etiquetas** ao terminar.'],
 'checklist': ['Estoque → Gerar Etiquetas de Produtos → Etiquetas Avulsas',
               'Código do produto (ou lupa) e nº de etiquetas',
               'Produto enviado para a lista (Imprimir)',
               'Impressora, Etiqueta Adesiva e modelo conferidos',
               'Modelo da etiqueta → Ok',
               'Etiquetas conferidas (tamanho = par)',
               'Arquivo de etiquetas limpo (Sim)'],
},
# ---------------------------------------------------------------- 4. FECHAMENTO DE VOLUME
{
 'id': 'fechamento-de-volumes', 'ordem': 4, 'nome': 'Fechamento de Volume', 'duracao': '13:10', 'accent': '#a78bfa',
 'objetivo': 'Fechar e identificar corretamente as caixas que saem da loja (remanejo, defeito, devolução ao fornecedor e devolução para loja), para que a mercadoria viaje protegida e seja reconhecida pelo CD e pela loja de destino.',
 'quando': ['Depois de montar o volume no BTA, com a caixa cheia e conferida.'],
 'antes': ['Separe **fita**, **estilete/tesoura**, **caneta**, os **rótulos** impressos (4 ou 5 por caixa) e a **placa** certa.',
           'Placa preenchida com **visto do gerente**, origem, destino, nota fiscal, volume e data.'],
 'passos': [
  {'t': 5, 'titulo': 'Feche a caixa com fita',
   'texto': ['Com a caixa cheia e tudo conferido, feche passando fita **em volta de toda a caixa**. Não pode ficar abertura nem parte mole por onde a mercadoria saia. Os produtos devem ficar firmes dentro da caixa para não amassar no transporte.'],
   'prints': [{'t': 0}, {'t': 38}]},
  {'t': 72, 'titulo': 'Reforce as laterais',
   'texto': ['Dependendo da caixa, passe fita também nas **laterais** e nos cantos para reforçar. Caixa mais mole precisa de mais reforço.'],
   'prints': [{'t': 72}, {'t': 96}]},
  {'t': 116, 'titulo': 'Caixa grande demais? Diminua a caixa',
   'texto': ['Se o produto fica **folgado** (caixa maior que o produto), diminua a caixa: passe o **estilete nas quinas laterais** na altura do produto, dobre as abas para dentro e feche de novo com fita (em cima, embaixo e no meio).',
             'Caixa na medida protege o produto e não amassa na entrega.'],
   'prints': [{'t': 132}, {'t': 184}]},
  {'t': 240, 'titulo': 'Conheça as placas',
   'texto': ['**Remanejo:** destino **R1** já impresso; você escreve só a loja de destino. **Defeito** e **Devolução ao Fornecedor:** destino **01 CD**, não se mexe. **Devolução Loja:** R1 + a loja que vai receber, e leva também a **folha de motivos**.',
             'Em todas: **visto do gerente**, **rótulo aqui**, **nota fiscal**, **volume** (ex.: 1/3) e **data** de saída. A área do CD fica em branco.'],
   'prints': [{'t': 264}, {'t': 300}, {'t': 336}, {'t': 366}]},
  {'t': 390, 'titulo': 'Folha de motivos da devolução para loja',
   'texto': ['Na devolução para loja, a loja que recebe precisa saber **por que** o produto voltou. A folha tem os motivos: **defeito, produto sem condição de venda, pé queimado, pé único, saci, pés trocados, código errado e sem brinde**. A folha tem duas partes: recorte e use uma por caixa.'],
   'prints': [{'t': 396}]},
  {'t': 436, 'titulo': 'Cole a placa na frente da caixa',
   'texto': ['A placa vai **na parte da frente**, bem visível e bem colada (fita em volta). Se a caixa for pequena demais, cole **em cima**.'],
   'prints': [{'t': 456}, {'t': 488}]},
  {'t': 496, 'titulo': 'Cole rótulos em vários lados',
   'texto': ['Cole um rótulo **no espaço da placa** e os outros nas **laterais, na tampa e atrás**. Se a caixa ficar embaixo de outras, ainda dá para identificar.',
             'Por isso imprima **4 ou 5 rótulos** por volume.'],
   'prints': [{'t': 548}, {'t': 590}]},
  {'t': 530, 'titulo': 'Tire ou cubra rótulos e placas antigas',
   'texto': ['Caixa reaproveitada chega com rótulo de outra loja ou placa do CD. **Retire**, **cole seu rótulo por cima** ou **rasure**, para a caixa não ser confundida com outro volume.',
             'O rótulo tem que sair **perfeito**. Se a impressora falhar ou rasurar, **reimprima**.'],
   'prints': [{'t': 600}, {'t': 618}]},
  {'t': 624, 'titulo': 'Devolução para loja: placa em cima + motivo marcado',
   'texto': ['Na devolução para loja, cole a placa **em cima** e passe fita em volta para firmar. Recorte a **folha de motivos**, cole atrás da caixa e **marque com caneta** o motivo da devolução.'],
   'prints': [{'t': 692}, {'t': 776}]},
 ],
 'atencao': ['Caixa **sem abertura** e sem folga: produto solto amassa ou se perde no transporte.',
             'Placa certa para cada tipo de envio, com **visto do gerente**.',
             '**Número da NF, volume (ex.: 2/5) e data** preenchidos na placa.',
             'Rótulos antigos de outra loja ou do CD devem ser **retirados, cobertos ou rasurados**.',
             'Rótulo falhado ou rasurado: **reimprima**.'],
 'checklist': ['Caixa cheia, conferida e sem folga (diminuída se precisar)',
               'Fita em volta de toda a caixa e laterais reforçadas',
               'Placa certa (Remanejo / Defeito / Devolução Fornecedor / Devolução Loja)',
               'Visto do gerente, destino, NF, volume e data preenchidos',
               'Placa colada na frente (ou em cima, se a caixa for pequena)',
               '4 ou 5 rótulos colados (placa, laterais, tampa, traseira)',
               'Rótulos e placas antigas retirados, cobertos ou rasurados',
               'Devolução para loja: folha de motivos colada e marcada'],
},
# ---------------------------------------------------------------- 5. DEFEITO
{
 'id': 'defeito', 'ordem': 5, 'nome': 'Defeito', 'duracao': '08:43', 'accent': '#f87171',
 'objetivo': 'Enviar ao **CD** os produtos com defeito da loja: marcar o produto como defeito no **SETA** (quando necessário), criar o volume na aba **Defeito** do BTA e gerar o **checkout da expedição**.',
 'quando': ['Cliente devolveu produto com defeito (processo feito pelo vendedor com o gerente) e o par chegou ao estoquista.',
            'Produto da loja com defeito de fábrica ou avariado, sem venda.'],
 'passos': [
  {'t': 23, 'titulo': 'BTA: aba Defeito → Criar Volume',
   'texto': ['No **Controle Remanejo Loja**, clique na aba **Defeito**. Ela tem só dois botões: **Criar Volume** e **Checkout Expedição**. Clique em **Criar Volume**.'],
   'prints': [{'t': 35, 'crop': BTA_MENU, 'hl': [H(35.3, 24.3, 3.8, 3.2, '1'), H(26.5, 29.4, 47, 4, '2 · Criar Volume')]}]},
  {'t': 51, 'titulo': 'Confira origem e destino e clique em Iniciar',
   'texto': ['A **origem** é a sua loja e o **destino é 001 CD**. Defeito vai **direto para o CD**; não mude o destino.',
             'Separe uma caixa do tamanho certo para os defeitos, sem espaço sobrando. Clique em **Iniciar** e confirme com **Sim**.'],
   'prints': [{'t': 51, 'crop': BTA_JANELA, 'hl': [H(26.4, 14, 20.8, 5, 'origem / 001 CD'), H(6.4, 12.2, 11.2, 3.8, 'Iniciar')]}]},
  {'t': 134, 'titulo': 'Bipe os defeitos',
   'texto': ['Bipe cada par com defeito. Eles aparecem na lista com a **quantidade total** embaixo.',
             'Se aparecer **"Nenhum produto com status Na Loja foi encontrado no controle de defeitos"**, o produto ainda está no estoque de venda (estoque 1). Faça antes o **tratamento no SETA** (passos 3 a 6) e depois bipe de novo.'],
   'prints': [{'t': 147, 'crop': BTA_JANELA, 'hl': [H(36.5, 40.8, 28.3, 20.4, 'produto não consta como defeito')]}]},
  {'t': 180, 'titulo': 'SETA: Estoque → Devolução ao Fornecedor',
   'texto': ['No SETA, entre em **Retaguarda** e abra o menu **Estoque → Devolução ao Fornecedor**. Na pergunta **"Deseja usar a tela para bipar produtos com defeito?"**, responda **Sim**.'],
   'prints': [{'t': 210, 'crop': SETA, 'hl': [H(13.3, 3.1, 3.7, 2.8, 'Estoque'), H(13.3, 34, 16, 3, 'Devolução ao Fornecedor')]},
              {'t': 218, 'crop': SETA, 'hl': [H(36.8, 41, 26.8, 19.6, 'Sim')]}]},
  {'t': 226, 'titulo': 'Clique em Marcar Defeito',
   'texto': ['Na tela **Devolução ao fornecedor**, clique em **Marcar Defeito** para mandar o produto do estoque de venda para o estoque de defeito.'],
   'prints': [{'t': 225, 'crop': SETA, 'hl': [H(30, 31.4, 9.5, 3.2, 'Marcar Defeito')]}]},
  {'t': 240, 'titulo': 'Informe o código e o tamanho',
   'texto': ['Digite o **código do produto** (sem o tamanho). Aparece a **grade** com o estoque de cada tamanho.',
             'Clique no **tamanho do par com defeito**. Atenção: no primeiro clique o sistema pula para o tamanho seguinte (clicou no 37, foi para o 38); **volte para o tamanho certo** e coloque **1** na coluna **Defeito**.'],
   'prints': [{'t': 300, 'crop': SETA, 'hl': [H(39.3, 28.3, 8, 3.4, 'código'), H(60.8, 48.1, 14.8, 3.2, 'tamanho → Defeito = 1')]}]},
  {'t': 318, 'titulo': 'Escolha o defeito, descreva e marque',
   'texto': ['No campo **Defeito**, pesquise e escolha o tipo (ex.: **descolamento**, descosturando). Em **Motivo/OBS** escreva qual pé e o problema (ex.: *"pé direito descolando"*) para o CD identificar melhor.',
             'Clique em **Marcar Defeito**, dê **OK** e feche. Volte ao BTA e bipe o par: agora ele entra na lista.'],
   'prints': [{'t': 300, 'crop': SETA, 'hl': [H(39.3, 46.3, 19.5, 10, 'Defeito + Motivo/OBS'), H(22.4, 26.8, 7.8, 3.2, 'Marcar Defeito')]}]},
  {'t': 386, 'titulo': 'Finalize o volume, imprima rótulos e prepare a placa',
   'texto': ['Com todos os defeitos bipados, clique em **Finalizar**. O sistema gera o **rótulo** (loja de origem → CD); imprima a quantidade para colar na caixa.',
             'Use a **placa de DEFEITO**: visto do gerente ou subgerente, origem (sua loja), destino **01 CD** já impresso, nota fiscal, volume e data de saída.'],
   'prints': [{'t': 415, 'crop': [21, 21, 56, 70], 'hl': [H(58, 34, 17.5, 6, 'visto do gerente'), H(58, 40.8, 17.5, 9, 'rótulo')]}]},
  {'t': 457, 'titulo': 'Checkout Expedição',
   'texto': ['Na aba Defeito, clique em **Checkout Expedição**. O destino já vem **001 CD** (não muda). Clique em **Iniciar** e confirme com **Sim**.',
             'Bipe **cada volume** (caixa) que você fez. Confira **Total Volumes** e **Qtde Itens** e clique em **Finalizar**.'],
   'prints': [{'t': 464, 'crop': [5, 5, 92, 84], 'hl': [H(41, 17.2, 14.5, 3.2, '001 CD'), H(59, 17.2, 12.2, 3.2, 'bipe o volume'), H(75, 14, 18.2, 6.8, 'totais'), H(6.4, 15, 11, 3.8, 'Iniciar')]}]},
  {'t': 496, 'titulo': 'Imprima o papel da Expedição',
   'texto': ['Ao finalizar sai o **papel da Expedição** (loja → CD) com a quantidade de volumes e de itens. Imprima: ele é usado para gerar a **nota fiscal** (módulo Notas Fiscais).'],
   'prints': [{'t': 501, 'crop': [23, 4, 54, 88], 'hl': []}]},
 ],
 'atencao': ['Defeito vai **sempre para 001 CD**: não altere o destino.',
             'Produto que dá **"não consta no controle de defeitos"** precisa ser marcado no SETA antes de bipar.',
             'Ao clicar no tamanho, o sistema **pula para o próximo**: confira o tamanho antes de marcar.',
             'Descreva o defeito e **qual pé** na observação.',
             'No checkout, bipe **todos os volumes**, não só um.'],
 'checklist': ['Par com defeito identificado e em mãos',
               'Se preciso: SETA → Estoque → Devolução ao Fornecedor → Marcar Defeito',
               'Tamanho certo, tipo de defeito e observação (qual pé)',
               'BTA → Defeito → Criar Volume (destino 001 CD) → Iniciar',
               'Defeitos bipados e Finalizar (rótulos impressos)',
               'Placa de DEFEITO preenchida e colada',
               'Checkout Expedição com todos os volumes bipados',
               'Papel da Expedição impresso → gerar nota fiscal'],
},
# ---------------------------------------------------------------- 6. REMANEJO
{
 'id': 'remanejo', 'ordem': 6, 'nome': 'Remanejo', 'duracao': '09:11', 'accent': '#4ade80',
 'objetivo': 'Separar e enviar os produtos que outras lojas pediram à sua loja, via **R1 (CD Remanejo)**: consultar os pedidos, montar os volumes, imprimir rótulos e placa e gerar o **checkout da expedição**.',
 'quando': ['Quando aparecer no BTA pedido de transferência (TRF) em aberto para a sua loja enviar.'],
 'passos': [
  {'t': 13, 'titulo': 'BTA: aba Remanejo → Pedido de TRF em Aberto',
   'texto': ['Antes de montar o remanejo, veja **o que cada loja está pedindo**. Na aba **Remanejo**, clique em **Pedido de TRF em Aberto**.'],
   'prints': [{'t': 20, 'crop': BTA_MENU, 'hl': [H(26.4, 24.3, 3.8, 3.2, '1'), H(26.5, 29.4, 47, 4, '2 · Pedido de TRF em Aberto')]}]},
  {'t': 30, 'titulo': 'Veja os pedidos e imprima a lista',
   'texto': ['Em **Saldo Pedidos de Transferência** aparecem todos os produtos pedidos: código, descrição, cor, **destino** (loja que pediu) e **saldo** (quantidade pedida).',
             'Clique em **Imprimir** para tirar o papel com todas as lojas.'],
   'prints': [{'t': 36, 'crop': BTA_JANELA, 'hl': [H(8.6, 21.6, 11.3, 4.2, 'Imprimir'), H(59.5, 26.5, 13, 56, 'destino'), H(72, 26.5, 5.5, 56, 'saldo')]}]},
  {'t': 82, 'titulo': 'Filtre uma loja por vez',
   'texto': ['Em **Destino**, escolha a loja (ex.: 048) e clique em **Filtrar**. Aparece só o que vai para ela; imprima a folha dessa loja e separe os produtos.'],
   'prints': [{'t': 110, 'crop': BTA_JANELA, 'hl': [H(34.4, 20, 14, 3.2, 'Destino'), H(8.4, 17.2, 11.4, 3.8, 'Filtrar')]}]},
  {'t': 146, 'titulo': 'Confira os pares e monte a caixa',
   'texto': ['Antes de criar o volume, confira cada par: **não está sujo, trocado nem com defeito**, tem condição de venda.',
             'Coloque na caixa só a quantidade que ela suporta. Se a loja pediu muitos produtos, faça **mais de um volume**.'],
   'dica': 'Não envie tudo de uma vez só porque a loja pediu: primeiro a caixa, depois a criação do volume.'},
  {'t': 184, 'titulo': 'Criar Volume: destino R1 e destino final',
   'texto': ['Clique em **Criar Volume**. A origem é a sua loja e o destino é sempre **R1 - CD Remanejo**: o volume passa pelo CD e depois segue para a loja.',
             'Na **lupa do Destino Final**, pesquise a loja (ex.: 048), selecione e clique em **Exportar**.'],
   'prints': [{'t': 213, 'crop': BTA_JANELA, 'hl': [H(30.5, 19.3, 26, 57, 'escolha a loja'), H(18, 21, 11.2, 4.2, 'Exportar')]},
              {'t': 218, 'crop': BTA_JANELA, 'hl': [H(26.3, 16.7, 20.5, 3, 'R1 - CD Remanejo'), H(26.3, 19.5, 20.5, 3, 'destino final'), H(6.4, 12.2, 11.2, 3.8, 'Iniciar')]}]},
  {'t': 223, 'titulo': 'Iniciar e bipar os produtos',
   'texto': ['Clique em **Iniciar** e confirme a loja com **Sim**. Bipe todos os pares da caixa. Confira no alto: **Itens** (produtos diferentes) e **Qtde** (total de pares). Se a caixa cabe 12, a quantidade tem que dar 12.',
             'Clique em **Finalizar**.'],
   'prints': [{'t': 293, 'crop': BTA_JANELA, 'hl': [H(18.5, 28.3, 28.5, 3.8, 'bipe os pares'), H(50.5, 13.8, 13.5, 5.5, 'Itens / Qtde'), H(6.4, 16.8, 11.2, 3.8, 'Finalizar')]}]},
  {'t': 270, 'titulo': 'Imprima os rótulos e preencha a placa de REMANEJO',
   'texto': ['Ao finalizar sai o **rótulo** na impressora (Argox/Datamax). Tire a quantidade para colar na caixa.',
             'Na **placa de REMANEJO**: visto do gerente, **origem** (sua loja), **destino R1/** + a loja (ex.: R1/48), **nota fiscal** (depois de emitida), **volume** e **data** em que o caminhão leva. A parte do CD fica em branco.'],
   'prints': [{'t': 301, 'crop': [20, 24, 58, 72], 'hl': []}]},
  {'t': 406, 'titulo': 'Perdeu o rótulo? Volumes em Aberto → Etiquetas',
   'texto': ['Para reimprimir um rótulo: **Volumes em Aberto**, escolha o **Destino** (a loja), **Filtrar**, selecione o volume e clique em **Etiquetas**.',
             '**Só dá para reimprimir antes de fazer o checkout**. Depois da expedição gerada, não dá mais.'],
   'prints': [{'t': 420, 'crop': BTA_JANELA, 'hl': [H(35.4, 18.4, 14.3, 3.2, 'Destino'), H(9.4, 16, 10.8, 4, 'Filtrar'), H(9.4, 24.6, 10.8, 4, 'Etiquetas')]}]},
  {'t': 434, 'titulo': 'Checkout Expedição com destino R1',
   'texto': ['Clique em **Checkout Expedição**. O destino vem **CD**: **troque para R1 - CD Remanejo**. Clique em **Iniciar** e confirme com **Sim**.',
             'Bipe **todos os volumes** que fez (não só um). Confira **Total Volumes** e **Qtde Itens** (ex.: 5 volumes, 30 itens) e clique em **Finalizar**.'],
   'prints': [{'t': 470, 'crop': [5, 5, 92, 70], 'hl': [H(41, 17.3, 14.5, 3, 'R1'), H(59, 17.3, 12.2, 3, 'bipe cada volume'), H(75, 14.2, 22, 6.5, 'totais')]}]},
  {'t': 529, 'titulo': 'Imprima a Expedição e gere a nota',
   'texto': ['Ao finalizar abre o papel da **Expedição** para imprimir na impressora da loja. Com ele você gera a **nota fiscal** (módulo Notas Fiscais) e completa a placa.'],
   'prints': [{'t': 501, 'mod': 'defeito', 'crop': [23, 4, 54, 88], 'hl': []}]},
 ],
 'atencao': ['Destino do volume e do checkout é sempre **R1 (CD Remanejo)**, nunca "CD" direto.',
             'Confira cada par (sujo, trocado, defeito) **antes** de criar o volume.',
             'Rótulo só pode ser reimpresso **antes do checkout**.',
             'No checkout, bipe **todos os volumes** e confira totais de volumes e itens.',
             'Placa de remanejo com **visto do gerente** e loja de destino (R1/loja).'],
 'checklist': ['Pedido de TRF em Aberto consultado e impresso por loja',
               'Pares conferidos (sem sujeira, troca ou defeito)',
               'Criar Volume: destino R1 + destino final da loja',
               'Pares bipados, Itens/Qtde conferidos e Finalizar',
               'Rótulos impressos e placa de REMANEJO preenchida',
               'Checkout Expedição com destino R1 e todos os volumes',
               'Papel da Expedição impresso → nota fiscal emitida'],
},
]
